import type {
  PlatformCapabilities,
  PlatformCopySpecs,
  PlatformImageSpecs,
} from "@paperclipai/shared";

interface PlatformSeedEntry {
  slug: string;
  name: string;
  category: string;
  sortOrder: number;
  capabilities: PlatformCapabilities;
  copySpecs: PlatformCopySpecs;
  imageSpecs: PlatformImageSpecs;
  description?: string;
  websiteUrl?: string;
}

// Fonte: docs/references/global-content-formats-atlas.md v3.1
export const SOCIAL_PLATFORMS_SEED: PlatformSeedEntry[] = [
  // ─── Meta Ecosystem ───────────────────────────────────────────────────────
  {
    slug: "instagram",
    name: "Instagram",
    category: "social",
    sortOrder: 10,
    description: "Plataforma de fotos, reels e stories com foco em descoberta visual.",
    websiteUrl: "https://instagram.com",
    capabilities: {
      supports_video: true,
      supports_carousel: true,
      supports_stories: true,
      supports_dm: true,
      supports_live: true,
      supports_ads: true,
      supports_scheduling: false,
      link_in_body: false,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "image",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 2200,
      max_title_chars: null,
      max_hashtags: 30,
      supports_mentions: true,
      supports_markdown: false,
      notes: "Link apenas na bio. API v21.0.",
    },
    imageSpecs: [
      { slot: "feed_square", width: 1080, height: 1080, aspect_ratio: "1:1", max_file_size_mb: 8, formats: ["jpg", "png"] },
      { slot: "feed_portrait", width: 1080, height: 1350, aspect_ratio: "4:5", max_file_size_mb: 8, formats: ["jpg", "png"] },
      { slot: "story", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 100, formats: ["jpg", "png", "mp4"], max_duration_seconds: 60 },
      { slot: "reel", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 100, formats: ["mp4"], max_duration_seconds: 90 },
      { slot: "carousel_slide", width: 1080, height: 1080, aspect_ratio: "1:1", max_file_size_mb: 8, formats: ["jpg", "png"] },
    ],
  },
  {
    slug: "whatsapp-business",
    name: "WhatsApp Business",
    category: "messaging",
    sortOrder: 20,
    description: "Canal de mensagens para negócios com Canais, Comunidades e Status.",
    websiteUrl: "https://business.whatsapp.com",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: true,
      supports_dm: true,
      supports_live: false,
      supports_ads: true,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "paid",
      primary_content_type: "mixed",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 4096,
      max_title_chars: null,
      max_hashtags: 0,
      supports_mentions: false,
      supports_markdown: false,
      notes: "Links permitidos no corpo. Sem hashtags.",
    },
    imageSpecs: [
      { slot: "image", width: 1280, height: 1280, aspect_ratio: "1:1", max_file_size_mb: 16, formats: ["jpg", "png", "webp"] },
      { slot: "video", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 16, formats: ["mp4", "3gp"], max_duration_seconds: 300 },
      { slot: "status", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 16, formats: ["jpg", "png", "mp4"] },
    ],
  },
  {
    slug: "facebook",
    name: "Facebook",
    category: "social",
    sortOrder: 30,
    description: "Grupos, Reels e Marketplace. Alcance via Reels compartilhados com Instagram.",
    websiteUrl: "https://facebook.com",
    capabilities: {
      supports_video: true,
      supports_carousel: true,
      supports_stories: true,
      supports_dm: true,
      supports_live: true,
      supports_ads: true,
      supports_scheduling: true,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "mixed",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 63206,
      max_title_chars: null,
      max_hashtags: null,
      supports_mentions: true,
      supports_markdown: false,
      notes: "Links no corpo. Hashtags suportados.",
    },
    imageSpecs: [
      { slot: "feed", width: 1200, height: 630, aspect_ratio: "1.91:1", max_file_size_mb: 10, formats: ["jpg", "png"] },
      { slot: "story", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 100, formats: ["jpg", "png", "mp4"], max_duration_seconds: 20 },
      { slot: "reel", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 100, formats: ["mp4"], max_duration_seconds: 90 },
    ],
  },
  {
    slug: "threads",
    name: "Threads",
    category: "social",
    sortOrder: 40,
    description: "Microblogging de conversas textuais e áudio nativo integrado ao Instagram.",
    websiteUrl: "https://threads.net",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: false,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "text",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 500,
      max_title_chars: null,
      max_hashtags: 0,
      supports_mentions: true,
      supports_markdown: false,
      notes: "API pública limitada (2026). Sem hashtags.",
    },
    imageSpecs: [
      { slot: "image", width: 1080, height: 1080, aspect_ratio: "1:1", max_file_size_mb: 10, formats: ["jpg", "png"] },
    ],
  },

  // ─── Video & Streaming ────────────────────────────────────────────────────
  {
    slug: "youtube",
    name: "YouTube",
    category: "video",
    sortOrder: 50,
    description: "VOD, Shorts, Lives e Comunidade. Motor de validação de marca 24/7.",
    websiteUrl: "https://youtube.com",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: true,
      supports_ads: true,
      supports_scheduling: true,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "video",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 5000,
      max_title_chars: 100,
      max_hashtags: 15,
      supports_mentions: true,
      supports_markdown: false,
      notes: "Thumbnail: 1280×720px, 2MB. Shorts monetização: 45% rev share a partir de 500 subs.",
    },
    imageSpecs: [
      { slot: "thumbnail", width: 1280, height: 720, aspect_ratio: "16:9", max_file_size_mb: 2, formats: ["jpg", "png"] },
      { slot: "vod", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 261120, formats: ["mp4", "mov", "avi"], max_duration_seconds: 43200 },
      { slot: "short", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 256, formats: ["mp4", "mov"], max_duration_seconds: 60 },
    ],
  },
  {
    slug: "tiktok",
    name: "TikTok",
    category: "video",
    sortOrder: 60,
    description: "Vídeos curtos com descoberta algorítmica. Série, LIVE e TikTok Shop (fora do BR).",
    websiteUrl: "https://tiktok.com",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: true,
      supports_live: true,
      supports_ads: true,
      supports_scheduling: false,
      link_in_body: false,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "video",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 2200,
      max_title_chars: null,
      max_hashtags: 20,
      supports_mentions: true,
      supports_markdown: false,
      notes: "Content Posting API gratuita, requer auditoria para direct post. TikTok Shop NÃO disponível no Brasil.",
    },
    imageSpecs: [
      { slot: "video", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 287, formats: ["mp4", "mov"], max_duration_seconds: 600 },
    ],
  },
  {
    slug: "kwai",
    name: "Kwai",
    category: "video",
    sortOrder: 70,
    description: "60M MAU Brasil. Vídeo curto, TeleKwai (micronovelas), Live Commerce.",
    websiteUrl: "https://kwai.com",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: true,
      supports_ads: true,
      supports_scheduling: false,
      link_in_body: false,
      link_penalty: false,
      has_api: false,
      api_type: "none",
      primary_content_type: "video",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: null,
      max_hashtags: null,
      supports_mentions: false,
      supports_markdown: false,
      notes: "Sem API orgânica pública. Apenas Kwai for Business (campanhas pagas). Zero-rating Claro.",
    },
    imageSpecs: [
      { slot: "video_short", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 100, formats: ["mp4"], max_duration_seconds: 60 },
      { slot: "telekwai", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 200, formats: ["mp4"], max_duration_seconds: 300 },
    ],
  },
  {
    slug: "twitch",
    name: "Twitch",
    category: "video",
    sortOrder: 80,
    description: "Livestreaming, Clips, VODs e Drops. Monetização global para Affiliates (mai/2026).",
    websiteUrl: "https://twitch.tv",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: true,
      supports_live: true,
      supports_ads: true,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "video",
      is_br_priority: false,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: 140,
      max_hashtags: null,
      supports_mentions: true,
      supports_markdown: false,
      notes: "Helix API v2 (fev/2026). AV1 beta (jan/2026).",
    },
    imageSpecs: [
      { slot: "stream", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 10000, formats: ["h264", "h265"] },
      { slot: "thumbnail", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 10, formats: ["jpg", "png"] },
      { slot: "clip", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 100, formats: ["mp4"], max_duration_seconds: 60 },
    ],
  },

  // ─── B2B & Communities ────────────────────────────────────────────────────
  {
    slug: "linkedin",
    name: "LinkedIn",
    category: "b2b",
    sortOrder: 90,
    description: "Thought Leadership, Documentos/Carrosséis, Newsletter, Live Events.",
    websiteUrl: "https://linkedin.com",
    capabilities: {
      supports_video: true,
      supports_carousel: true,
      supports_stories: false,
      supports_dm: true,
      supports_live: true,
      supports_ads: true,
      supports_scheduling: true,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "mixed",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 3000,
      max_title_chars: null,
      max_hashtags: null,
      supports_mentions: true,
      supports_markdown: false,
      notes: "Newsletter: 125.000 chars, cover 1920×1080px. Open rate médio 42%. Live: RTMP 720p-1080p.",
    },
    imageSpecs: [
      { slot: "post", width: 1200, height: 627, aspect_ratio: "1.91:1", max_file_size_mb: 5, formats: ["jpg", "png"] },
      { slot: "carousel_pdf", width: 1080, height: 1080, aspect_ratio: "1:1", max_file_size_mb: 100, formats: ["pdf"] },
      { slot: "video", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 200, formats: ["mp4"], max_duration_seconds: 600 },
    ],
  },
  {
    slug: "discord",
    name: "Discord",
    category: "community",
    sortOrder: 100,
    description: "Canais de Voz/Texto, Stage Channels, Forum Channels e Server Subscriptions.",
    websiteUrl: "https://discord.com",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: true,
      supports_live: true,
      supports_ads: false,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "text",
      is_br_priority: false,
    },
    copySpecs: {
      max_body_chars: 2000,
      max_title_chars: null,
      max_hashtags: 0,
      supports_mentions: true,
      supports_markdown: true,
      notes: "Nitro: 4.000 chars. Embeds: 4.096 chars. Markdown Discord (sem HTML). API v10 — breaking change fev/2026.",
    },
    imageSpecs: [
      { slot: "attachment", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 10, formats: ["jpg", "png", "gif", "mp4"] },
    ],
  },

  // ─── Forums & Tech Aggregators ────────────────────────────────────────────
  {
    slug: "reddit",
    name: "Reddit",
    category: "forum",
    sortOrder: 110,
    description: "Threads, AMA, Galleries. Fonte primária para IAs de busca. Regra 90/10.",
    websiteUrl: "https://reddit.com",
    capabilities: {
      supports_video: true,
      supports_carousel: true,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: true,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "paid",
      primary_content_type: "text",
      is_br_priority: false,
    },
    copySpecs: {
      max_body_chars: 40000,
      max_title_chars: null,
      max_hashtags: 0,
      supports_mentions: true,
      supports_markdown: true,
      notes: "API: OAuth2, paga para volume. Sem hashtags.",
    },
    imageSpecs: [
      { slot: "gallery", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 20, formats: ["jpg", "png", "gif"] },
    ],
  },
  {
    slug: "hacker-news",
    name: "Hacker News",
    category: "forum",
    sortOrder: 120,
    description: "Links Curados, Show HN, Ask HN. Algoritmo de velocidade de upvotes na 1ª hora.",
    websiteUrl: "https://news.ycombinator.com",
    capabilities: {
      supports_video: false,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: false,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "text",
      is_br_priority: false,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: null,
      max_hashtags: 0,
      supports_mentions: false,
      supports_markdown: false,
      notes: "Plain text. Sem markdown. Karma > volume de posts. Ceticismo técnico = engajamento.",
    },
    imageSpecs: [],
  },
  {
    slug: "indie-hackers",
    name: "Indie Hackers",
    category: "forum",
    sortOrder: 130,
    description: "Páginas de Produto com métricas, Milestones, Interviews. Founder-to-founder trust.",
    websiteUrl: "https://indiehackers.com",
    capabilities: {
      supports_video: false,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: false,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: false,
      api_type: "none",
      primary_content_type: "text",
      is_br_priority: false,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: null,
      max_hashtags: 0,
      supports_mentions: false,
      supports_markdown: true,
      notes: "Sem API pública. Posts sem números (métricas) são ignorados. metricsRequired: true.",
    },
    imageSpecs: [],
  },
  {
    slug: "quora",
    name: "Quora",
    category: "forum",
    sortOrder: 140,
    description: "Q&A de cauda longa e Spaces. Canal de indexação de autoridade por LLMs.",
    websiteUrl: "https://quora.com",
    capabilities: {
      supports_video: false,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: true,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: false,
      api_type: "none",
      primary_content_type: "text",
      is_br_priority: false,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: 50,
      max_hashtags: 0,
      supports_mentions: false,
      supports_markdown: false,
      notes: "4-6M visitas BR/mês. Respostas indexadas por LLMs. Sem API pública.",
    },
    imageSpecs: [],
  },
  {
    slug: "product-hunt",
    name: "Product Hunt",
    category: "forum",
    sortOrder: 150,
    description: "Launches com 150k-250k visitantes únicos/dia. API GraphQL v2.",
    websiteUrl: "https://producthunt.com",
    capabilities: {
      supports_video: true,
      supports_carousel: true,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: false,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "mixed",
      is_br_priority: false,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: 60,
      max_hashtags: 0,
      supports_mentions: false,
      supports_markdown: false,
      notes: "Tagline: 60 chars (outcome > hype). Shoutouts: máx 3. Launch apenas via UI.",
    },
    imageSpecs: [
      { slot: "thumbnail", width: 640, height: 480, aspect_ratio: "4:3", max_file_size_mb: 5, formats: ["jpg", "png"] },
      { slot: "gallery", width: 1270, height: 760, aspect_ratio: "5:3", max_file_size_mb: 5, formats: ["jpg", "png"] },
      { slot: "video", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 100, formats: ["mp4"], max_duration_seconds: 90 },
    ],
  },

  // ─── Publishing & Owned Audience ─────────────────────────────────────────
  {
    slug: "blog",
    name: "Blog",
    category: "publishing",
    sortOrder: 160,
    description: "Artigos SEO/AEO, Case Studies, Lead Magnets. Answer-First com TL;DR.",
    websiteUrl: null as unknown as string,
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: false,
      supports_scheduling: true,
      link_in_body: true,
      link_penalty: false,
      has_api: false,
      api_type: "none",
      primary_content_type: "text",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: null,
      max_hashtags: null,
      supports_mentions: false,
      supports_markdown: true,
      notes: "Schema JSON-LD + LocalBusiness markup. AEO: H2s como perguntas. GEO: citável por LLMs.",
    },
    imageSpecs: [
      { slot: "featured", width: 1200, height: 630, aspect_ratio: "1.91:1", max_file_size_mb: 5, formats: ["jpg", "png", "webp"] },
    ],
  },
  {
    slug: "substack",
    name: "Substack",
    category: "publishing",
    sortOrder: 170,
    description: "Paid Newsletter, Substack Notes (descoberta), Podcasts/Vídeo integrados.",
    websiteUrl: "https://substack.com",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: false,
      supports_scheduling: true,
      link_in_body: true,
      link_penalty: false,
      has_api: false,
      api_type: "none",
      primary_content_type: "text",
      is_br_priority: false,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: null,
      max_hashtags: null,
      supports_mentions: false,
      supports_markdown: true,
      notes: "Fee: 10% + Stripe ≈ 13-16%. Open rate: 30-60%. 50%+ novos subscribers via Notes (2026). canSchedule: true.",
    },
    imageSpecs: [
      { slot: "cover", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 5, formats: ["jpg", "png"] },
    ],
  },
  {
    slug: "github",
    name: "GitHub",
    category: "publishing",
    sortOrder: 180,
    description: "README como landing técnica, Discussions, Releases, Pages, Sponsors.",
    websiteUrl: "https://github.com",
    capabilities: {
      supports_video: false,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: false,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "text",
      is_br_priority: false,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: 350,
      max_hashtags: 20,
      supports_mentions: true,
      supports_markdown: true,
      notes: "README: 512KB via API. Topics: até 20. Bio: 160 chars. API REST v3 + GraphQL v4. Rate: 5.000 pontos/hora.",
    },
    imageSpecs: [
      { slot: "social_preview", width: 1280, height: 640, aspect_ratio: "2:1", max_file_size_mb: 1, formats: ["jpg", "png"] },
    ],
  },

  // ─── Microblog & Cronological ─────────────────────────────────────────────
  {
    slug: "twitter-x",
    name: "Twitter/X",
    category: "microblog",
    sortOrder: 190,
    description: "Posts, Carrossel, Spaces, Artigos longos (Premium). Links penalizam alcance.",
    websiteUrl: "https://x.com",
    capabilities: {
      supports_video: true,
      supports_carousel: true,
      supports_stories: false,
      supports_dm: true,
      supports_live: true,
      supports_ads: true,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: true,
      has_api: true,
      api_type: "paid",
      primary_content_type: "text",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 280,
      max_title_chars: null,
      max_hashtags: 1,
      supports_mentions: true,
      supports_markdown: false,
      notes: "Links penalizam -8x alcance — colocar no 1º comentário. Replies valem 15x mais que likes. Premium: 25k chars.",
    },
    imageSpecs: [
      { slot: "post_landscape", width: 1200, height: 675, aspect_ratio: "16:9", max_file_size_mb: 5, formats: ["jpg", "png"] },
      { slot: "post_square", width: 1080, height: 1080, aspect_ratio: "1:1", max_file_size_mb: 5, formats: ["jpg", "png"] },
      { slot: "post_portrait", width: 1080, height: 1350, aspect_ratio: "4:5", max_file_size_mb: 5, formats: ["jpg", "png"] },
      { slot: "gif", width: 1280, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 15, formats: ["gif"], max_duration_seconds: null as unknown as number },
    ],
  },
  {
    slug: "bluesky",
    name: "Bluesky",
    category: "microblog",
    sortOrder: 200,
    description: "Posts, Carrossel, Custom Feeds, Starter Packs. Links NÃO penalizados.",
    websiteUrl: "https://bsky.app",
    capabilities: {
      supports_video: true,
      supports_carousel: true,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: false,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "text",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 300,
      max_title_chars: null,
      max_hashtags: null,
      supports_mentions: true,
      supports_markdown: false,
      notes: "300 grafemas / 3.000 bytes UTF-8. API gratuita via AT Protocol: 1.666 posts/hora. BR = 3º maior mercado global.",
    },
    imageSpecs: [
      { slot: "post_square", width: 1000, height: 1000, aspect_ratio: "1:1", max_file_size_mb: 1, formats: ["jpg", "png"] },
      { slot: "post_landscape", width: 1000, height: 563, aspect_ratio: "16:9", max_file_size_mb: 1, formats: ["jpg", "png"] },
      { slot: "post_portrait", width: 800, height: 1000, aspect_ratio: "4:5", max_file_size_mb: 1, formats: ["jpg", "png"] },
      { slot: "video", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 100, formats: ["mp4"], max_duration_seconds: 180 },
    ],
  },

  // ─── Visual & Shopping ────────────────────────────────────────────────────
  {
    slug: "pinterest",
    name: "Pinterest",
    category: "social",
    sortOrder: 210,
    description: "Standard Pins (evergreen), Idea Pins, Video Pins. 631M MAU. BR = 2º maior mercado.",
    websiteUrl: "https://pinterest.com",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: true,
      supports_dm: false,
      supports_live: false,
      supports_ads: true,
      supports_scheduling: true,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "private",
      primary_content_type: "image",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 500,
      max_title_chars: 100,
      max_hashtags: null,
      supports_mentions: false,
      supports_markdown: false,
      notes: "Título: 40 chars visíveis no feed. Intenção de compra 2.2x maior que outras redes. 96% buscas unbranded.",
    },
    imageSpecs: [
      { slot: "standard_pin", width: 1000, height: 1500, aspect_ratio: "2:3", max_file_size_mb: 32, formats: ["jpg", "png", "webp"] },
      { slot: "square_pin", width: 1000, height: 1000, aspect_ratio: "1:1", max_file_size_mb: 32, formats: ["jpg", "png", "webp"] },
      { slot: "long_pin", width: 1000, height: 2100, aspect_ratio: "1:2.1", max_file_size_mb: 32, formats: ["jpg", "png"] },
      { slot: "idea_pin", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 100, formats: ["jpg", "png", "mp4"] },
      { slot: "video_pin", width: 1080, height: 1920, aspect_ratio: "9:16", max_file_size_mb: 2048, formats: ["mp4", "mov"], max_duration_seconds: 1800 },
    ],
  },

  // ─── Messaging & Broadcast ────────────────────────────────────────────────
  {
    slug: "telegram",
    name: "Telegram",
    category: "messaging",
    sortOrder: 220,
    description: "Canais (100% reach), Supergrupos até 200k membros, Bots, Mini Apps (TON).",
    websiteUrl: "https://telegram.org",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: true,
      supports_live: false,
      supports_ads: true,
      supports_scheduling: true,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "public",
      primary_content_type: "mixed",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 4096,
      max_title_chars: null,
      max_hashtags: null,
      supports_mentions: true,
      supports_markdown: true,
      notes: "Caption de mídia: 1.024 chars. MarkdownV2 + HTML nativo. Álbum: até 10 itens. BR = 5º maior mercado global.",
    },
    imageSpecs: [
      { slot: "image", width: 1280, height: 1280, aspect_ratio: "1:1", max_file_size_mb: 50, formats: ["jpg", "png"] },
      { slot: "video", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 50, formats: ["mp4"], max_duration_seconds: 3600 },
    ],
  },

  // ─── Podcast & Audio ─────────────────────────────────────────────────────
  {
    slug: "spotify",
    name: "Spotify",
    category: "podcast",
    sortOrder: 230,
    description: "Podcast de áudio e Vídeo Podcast (2x crescimento BR em 12 meses). Partner Program.",
    websiteUrl: "https://spotify.com",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: true,
      supports_scheduling: true,
      link_in_body: false,
      link_penalty: false,
      has_api: true,
      api_type: "private",
      primary_content_type: "audio",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: null,
      max_hashtags: 0,
      supports_mentions: false,
      supports_markdown: false,
      notes: "Distribution API (jan/2026): apenas hosts parceiros. Partner Program BR NÃO disponível. Duração máx: 12h.",
    },
    imageSpecs: [
      { slot: "artwork", width: 3000, height: 3000, aspect_ratio: "1:1", max_file_size_mb: 10, formats: ["jpg", "png", "tiff"] },
      { slot: "video_podcast", width: 1920, height: 1080, aspect_ratio: "16:9", max_file_size_mb: 2048, formats: ["mp4", "mov"] },
    ],
  },
  {
    slug: "apple-podcasts",
    name: "Apple Podcasts",
    category: "podcast",
    sortOrder: 240,
    description: "37,5% dos downloads globais. BR = 2º maior mercado global de podcasts. Artwork obrigatório 3000px.",
    websiteUrl: "https://podcasts.apple.com",
    capabilities: {
      supports_video: true,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: false,
      supports_scheduling: false,
      link_in_body: false,
      link_penalty: false,
      has_api: false,
      api_type: "none",
      primary_content_type: "audio",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: null,
      max_title_chars: null,
      max_hashtags: 0,
      supports_mentions: false,
      supports_markdown: false,
      notes: "Subscriptions: Apple retém 30% ano 1, 15% ano 2+. Sem API de publicação — apenas via hosts parceiros RSS.",
    },
    imageSpecs: [
      { slot: "artwork", width: 3000, height: 3000, aspect_ratio: "1:1", max_file_size_mb: 10, formats: ["jpg", "png"] },
    ],
  },

  // ─── Local SEO ────────────────────────────────────────────────────────────
  {
    slug: "google-business",
    name: "Google Meu Negócio",
    category: "local",
    sortOrder: 250,
    description: "Posts Update/Offer/Event, Review Management, Q&A. AI Overviews puxam dados do GBP.",
    websiteUrl: "https://business.google.com",
    capabilities: {
      supports_video: false,
      supports_carousel: false,
      supports_stories: false,
      supports_dm: false,
      supports_live: false,
      supports_ads: true,
      supports_scheduling: false,
      link_in_body: true,
      link_penalty: false,
      has_api: true,
      api_type: "private",
      primary_content_type: "text",
      is_br_priority: true,
    },
    copySpecs: {
      max_body_chars: 1500,
      max_title_chars: null,
      max_hashtags: 0,
      supports_mentions: false,
      supports_markdown: false,
      notes: "API PRIVADA: requer aprovação formal (60+ dias, 300 QPM). canSchedule: false (v4.9). Update expira em 7 dias.",
    },
    imageSpecs: [
      { slot: "post", width: 1200, height: 900, aspect_ratio: "4:3", max_file_size_mb: 5, formats: ["jpg", "png"] },
      { slot: "logo", width: 720, height: 720, aspect_ratio: "1:1", max_file_size_mb: 5, formats: ["jpg", "png"] },
      { slot: "cover", width: 1024, height: 575, aspect_ratio: "16:9", max_file_size_mb: 5, formats: ["jpg", "png"] },
    ],
  },
];
