import fs from "node:fs";
import path from "node:path";

const localesDir = "ui/src/i18n/locales";
const referenceLocale = "en";
const outputDir = "ui/src/i18n/generated";
const outputFile = path.join(outputDir, "locales-metadata.ts");
const COMPLETION_THRESHOLD = 0.2; // A locale is "translated" if at least 20% of its strings differ from English.

function countKeys(obj) {
  let count = 0;
  for (const key in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, key)) {
      if (typeof obj[key] === "object" && obj[key] !== null) {
        count += countKeys(obj[key]);
      } else {
        count++;
      }
    }
  }
  return count;
}

function countMatchingValues(obj1, obj2) {
  let matchingCount = 0;
  for (const key in obj1) {
    if (Object.prototype.hasOwnProperty.call(obj1, key) && Object.prototype.hasOwnProperty.call(obj2, key)) {
      const val1 = obj1[key];
      const val2 = obj2[key];
      if (typeof val1 === 'object' && val1 !== null && typeof val2 === 'object' && val2 !== null) {
        matchingCount += countMatchingValues(val1, val2);
      } else if (val1 === val2) {
        matchingCount++;
      }
    }
  }
  return matchingCount;
}

function analyzeLocales() {
  const referenceFilePath = path.join(localesDir, `${referenceLocale}.json`);
  if (!fs.existsSync(referenceFilePath)) {
    console.error(`Reference locale file not found: ${referenceFilePath}`);
    process.exit(1);
  }

  const referenceMessages = JSON.parse(fs.readFileSync(referenceFilePath, "utf-8"));
  const referenceKeyCount = countKeys(referenceMessages);

  const localeFiles = fs.readdirSync(localesDir).filter((file) => file.endsWith(".json"));

  const analysis = localeFiles.map((file) => {
    const locale = path.basename(file, ".json");
    if (locale === referenceLocale) {
      return { locale, completion: 1 }; // English is always 100% complete
    }
    const messages = JSON.parse(fs.readFileSync(path.join(localesDir, file), "utf-8"));
    const matchingValues = countMatchingValues(referenceMessages, messages);
    const totalKeys = referenceKeyCount;
    // Calculate the percentage of *different* values
    const completion = 1 - (matchingValues / totalKeys);
    return { locale, completion };
  });

  const sufficientlyTranslated = analysis
    .filter(({ completion }) => completion >= COMPLETION_THRESHOLD)
    .map(({ locale }) => locale);

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputContent = `// This file is auto-generated by scripts/analyze-locales.mjs. Do not edit manually.

export const sufficientlyTranslatedLocales: string[] = ${JSON.stringify(sufficientlyTranslated, null, 2)};
`;

  fs.writeFileSync(outputFile, outputContent, "utf-8");

  console.log(`Locale analysis complete. Found ${sufficientlyTranslated.length} sufficiently translated locales.`);
  console.log(`Results written to ${outputFile}`);
}

analyzeLocales();
